name: magnetfruit_avocadorm
version: 0.1.4
description: 'ORM to perform CRUD operations on entities.'
author: Zyrthofar <zyrthofar@magnetfruit.com>
homepage: 'http://www.magnetfruit.com/avocadorm/'
dependencies:
  magnetfruit_entity:
    git:
      url: https://github.com/ProgrammersForABetterTomorrowYesterday/entity.git
      ref: development
  magnetfruit_database_handler: ">=0.1.0 <0.2.0"
dev_dependencies:
  magnetfruit_mysql_database_handler: ">=0.1.0 <0.2.0"
  unittest: any
  mock: any
