name: magnetfruit_avocadorm
version: 0.1.0
description: 'Lightweight ORM, connecting entities and database in a CRUD manner.'
author: Zyrthofar <zyrthofar@magnetfruit.com>
homepage: 'www.magnetfruit.com/avocadorm/'
dependencies:
  magnetfruit_entity: any
  magnetfruit_database_handler: any
dev_dependencies:
  magnetfruit_mysql_database_handler: any
  unittest: any
  mock: any
