part of magnetfruit_avocadorm;

/// An exception that was generated by the [Avocadorm] class.
class AvocadormException implements Exception {

  /// The message of what went wrong.
  String message;

  /**
   * Creates an [AvocadormException] that can be thrown.
   */
  AvocadormException([this.message = '']);

  /// String representation of the exception message.
  String toString() => "AvocadormException: $message";

}
