part of resource;

/// An exception that was generated by the [Resource] class.
class ResourceException implements Exception {

  /// The message of what went wrong.
  String message;

  /**
   * Creates a [ResourceException] that can be thrown.
   */
  ResourceException([this.message = '']);

  /// String representation of the exception message.
  String toString() => "ResourceException: $message";

}
